import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Noto_Sans_Arabic } from 'next/font/google'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const notoArabic = Noto_Sans_Arabic({
  subsets: ['arabic'],
  weight: ['600', '900'], // اختياري
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${notoArabic.className} bg`}
      >
        {children}
      </body>
    </html>
  );
}
